### ISSUE TITLE
[Request] Add Mines by PCPSells to work with Tokens

### ISSUE THREAD

**Issue by RoyalityOfisl** [GC-spigot/Tokens#18] opened 2020-09-27 13:32 UTC
**Describe the feature**
Hello there, I hope you'll be able to add PCPSells Mines plugins to work with Tokens, since It's really good and awesome mine plugin hopefully you'll add support for it.

https://www.spigotmc.org/resources/mines-%C2%BB-1-7-1-16-2-%E2%80%A2-unique-features-%E2%80%A2-api.63552/

**Comment by myiume** [comment] 2020-09-29 11:02
Duplicate of #17

**Closed** 2020-09-29 11:02 UTC
Labels: Request
