### ISSUE TITLE
[Issue] Explosive Enchant Causing Ghost blocks

### ISSUE THREAD

**Issue by xZenithx** [GC-spigot/Tokens#74] opened 2021-02-22 19:56 UTC
**Describe the bug**
If you have the explosive enchant on a pickaxe and just break blocks it causes ghost blocks for you and others.

**To Reproduce**
I would assume just use explosive

**Screenshots / Video**
https://www.youtube.com/watch?v=MTQFK1-eU7U

**Server Information (please complete the following information):**
- Minecraft Version [PaperSpigot 1.16.5]
- Plugin Version [2.9.2]

**Comment by GC-spigot** [comment] 2021-02-22 20:16
That’s caused by an anticheat or a plugin blocking block breaks. What plugins are you using?

**Comment by xZenithx** [comment] 2021-02-22 20:33
Plugins (29): ChatInjector, CoreProtect, EpicRename, Essentials, EssentialsChat, EssentialsSpawn, EZBlocks*, FastAsyncWorldEdit (WorldEdit), FlightControl, Gatekeeper*, GroupManager, LiteBans, Multiverse-Core, NoCheatPlus, OpenInv, PlaceholderAPI, Playtimes*, Prison, ProtocolLib, RealScoreboard, SuperbVote, SuperVanish, TAB, Tokens, UVoteParty*, Vault, VoidGenerator, Votifier, WorldGuard

**Comment by blek-id** [comment] 2021-03-26 18:28
It was FAWE that is causing the ghost block

**Comment by GC-spigot** [comment] 2021-03-26 20:55
Should be fixed for next update

**Closed as completed by GC-spigot** 2021-03-26 20:55 UTC
Labels: Issue
