### ISSUE TITLE
[Issue] Shockwave enchant does not work.

### ISSUE THREAD

**Issue by Projecki** [GC-spigot/Tokens#7] opened 2020-09-21 21:47 UTC
**Describe the bug**
Shockwave enchant does not actually mine a layer of the mine. It does give you the blocks a shockwave would grant you when mining but it does not destroy those blocks in the mine.

https://pastebin.com/HvCXxYRU

**To Reproduce**
Mine with shockwave enchant.

**Server Information (please complete the following information):**
 - Tuinity 1.16.3
- Tokens 2.7.7

**Comment by myiume** [comment] 2020-09-21 23:04
That is because your FAWE version is not suitable for your server version. You are most likely on a 1.12 server running the 1.13+ FAWE Version. Am I right?

**Comment by Projecki** [comment] 2020-09-21 23:06
No, I am on FAWE 1.16-374.

**Comment by Projecki** [comment] 2020-09-21 23:15
Retested on latest build 376 and issue persists.

**Comment by myiume** [comment] 2020-09-21 23:46
![image](https://user-images.githubusercontent.com/3586926/93832264-d7cefe80-fc7d-11ea-96c7-dc0ff14ab837.png)

**Comment by myiume** [comment] 2020-09-21 23:47
You are on a pre 1.13 server with a FAWE version meant for 1.16, hence the name, FAWE 1.16-374 <- Fast Async World Edit for Minecraft 1.16 - build 374.

**Comment by myiume** [comment] 2020-09-21 23:50
Please use a FAWE version appropriate for your minecraft version. https://intellectualsites.github.io/download/fawe.html and select your proper version here.

**Comment by myiume** [comment] 2020-09-21 23:53
Will investigate and get back to you with more info 👍

**Comment by Projecki** [comment] 2020-09-22 00:40
I was able to replicate this issue with most enchants that use FAWE.

**Comment by myiume** [comment] 2020-09-22 18:41
The issue is not caused by the enchants, but by the API base. FAWE integration is a bit messed up. Working on a fix. Will keep you updated.

**Comment by Projecki** [comment] 2020-09-30 22:04
Okay!

**Comment by BluueJay** [comment] 2020-10-02 21:17
Any updates on this bug, still occurring for Sphered/Shockwave on following versions:

Tokens [v2.8.3](https://www.spigotmc.org/resources/⚡%EF%B8%8F-tokens-⚡%EF%B8%8F-40-enchantments-⭕-expansions-⭕-1-8-1-16-3-20-off.79668/update?update=363972)
FAWE v1.16-377
Latest Tuinity build (1.16.3)

**Comment by Projecki** [comment] 2020-10-03 21:50
Not sure if 2.8.3 meant to fix this but can confirm along with BluueJay that this still occurs

**Comment by myiume** [comment] 2020-10-05 12:39
Issue fixed. Will be released in the next version.

**Closed by myiume** 2020-10-05 12:39 UTC
Labels: Issue, bug
