### ISSUE TITLE
EzBlocks[Issue]

### ISSUE THREAD

**Issue by ImAlexGG** [GC-spigot/Tokens#38] opened 2020-10-25 19:49 UTC
**Describe the bug**
When i tested the block counter of EzBlocks with tokens the unique explode enchantment that works with the ezblocks its the laser, the other ones, shockwave, sphered.... dont rise then number of broke blocks.

**To Reproduce**
A way to reproduce the video

**Screenshots / Video**

**Server Information (please complete the following information):**
 - Minecraft Version [1.12.2]
- Plugin Version [2.8.5]

**Comment by myiume** [comment] 2020-10-26 02:34
The EZBlocks implementation needs some changes in the Enchantments that trigger blockBreaks. Currently Laser was the only one that was updated to the new API. Others will come soon. ;)

So Laser is working as intended?

Great to hear <3

**Comment by ImAlexGG** [comment] 2020-10-26 04:28
Yes Laser works perfectly, in the mines that i tested it, i have in my
mines from A to Z all ores, all ores blocks, ender stone. Then pmines uses
clays and vips the best one has obsidian.

**Comment by myiume** [comment] 2020-12-01 02:08
This has already been fixed and released in version 2.9.1

**Closed by myiume** 2020-12-01 02:08 UTC
Labels: Issue, bug
