### ISSUE TITLE
[Issue] TokenMiner doesn't load

### ISSUE THREAD

**Issue by ImAlexGG** [GC-spigot/Tokens#37] opened 2020-10-24 09:09 UTC
**Describe the bug**
When i place the TokenMiner jar in the tokens plugin, the plugin gets disabled, so it doesnt work

**To Reproduce**
A way to reproduce the video

**Screenshots / Video**

![image](https://user-images.githubusercontent.com/72762528/97078019-29560a80-15e9-11eb-85d6-7f4e190bccc3.png)

![image](https://user-images.githubusercontent.com/72762528/97078027-3e329e00-15e9-11eb-845e-5390b609d4cb.png)

![image](https://user-images.githubusercontent.com/72762528/97078035-48549c80-15e9-11eb-90ce-8263c74ab6aa.png)

![image](https://user-images.githubusercontent.com/72762528/97078044-51de0480-15e9-11eb-8ac5-d86bf35cb3f7.png)

**Server Information (please complete the following information):**
 - Minecraft Version [spigot 1.12.2]
- Plugin Version [2.8.5_1]

**Comment by myiume** [comment] 2020-11-02 21:57
I have improved the modules loading system so it won't deactivate the plugin if a broken enchant is found. 

The Tokenminer will be fixed soon as well.

**Comment by myiume** [comment] 2020-12-01 02:06
TokenMiner has been remade. It will now work as intended. Coming next release.

**Closed by myiume** 2020-12-01 02:06 UTC
Labels: Issue, bug
