### ISSUE TITLE
[Issue] AutoSell hook issues

### ISSUE THREAD

**Issue by BluueJay** [GC-spigot/Tokens#34] opened 2020-10-20 11:24 UTC
**Describe the bug**
AutoSell (dev version, pinned in PAPI help-chat discord) works flawlessly with 1.16.3 independantly however once I enable/install the Tokens plugin, AutoSell stops automatically selling and begins to automatically smelt cobblestone->stone, ores->ingots etc.

**To Reproduce**
Test AutoSell with 1.16.3, and then install Tokens.

**Server Information (please complete the following information):**
Server/MC version: 1.16.3 (Tuinity de1983b)
Tokens version: 2.8.5 (latest)

**Comment by BluueJay** [comment] 2020-10-21 13:10
Just an update on this issue after discussions with Myiume.

**While using 1.16.3** I've tried:
- Using the latest public version of AutoSell (1.9.3, intended for 1.15 but was told to try) instead of the pinned dev version for 1.16.3 in the PAPI HelpChat discord.
- Using Paper instead of Tuinity.
- Changing the AutoSell shop names.
- Changing the WorldGuard regions.
- Changing the hook within the AutoSell config from WorldGuard -> JetsPrisonMines
- Having * permissions and default permissions.

Issue still persists.

**Comment by myiume** [comment] 2020-10-26 02:36
Issue was caused by AutoSell. Fixed on version 2.8.6-DEV

**Closed** 2020-10-26 03:09 UTC
Labels: Issue
